### ISSUE TITLE
Unable to get the plugin to work

### ISSUE THREAD

**Issue by dangitdang** [blacroix/inkdrop-toc#1]
Hi I've installed the plugin but not sure why the table of content is not getting generated. For example I have the following markdown
```
# Table of Contents
##### Create Admin User in DB
##### Run Service
##### Remove Service
```
I'm assuming the TOC will be generated automatically? Am I doing something wrong?

**Comment by blacroix** [comment]
Hi!
Yes TOC is generated automatically.
Headers should be consecutive to work, you should try:
```
# Table of Contents
# Something header 2
## Something header 3
### Something header 4
```
Can you try this plz?
