### ISSUE TITLE
It won't work well

### ISSUE THREAD

**Issue by tkybpp** [blacroix/inkdrop-toc#2]
hi @blacroix 

I checked this comment: https://github.com/blacroix/inkdrop-toc/issues/1#issuecomment-399001717
```
# Table of Contents
# Something header 2
## Something header 3
### Something header 4
```
But it won't work.
Do you have any idea?

<img width="792" alt="ss 2019-01-08 23 27 34" src="https://user-images.githubusercontent.com/2084386/50836670-17b45c00-139d-11e9-956b-00f1d01bf17d.png">

My environment:
- Platform: (macOS)
- Platform version: (Sierra/10/13.05)
- App Version: (3.24.0)

**Comment by blacroix** [comment]
Hi @tkybpp is plugin active? Please check your developer console to see if you have an error?

**Comment by tkybpp** [comment]
It solved, it was stupid mistake.
https://github.com/inkdropapp/inkdrop-toc/pull/1
